export const CATEGORY_LIST_LOAD_SUCCESS = "CATEGORY_LIST_LOAD_SUCCESS";

export const PRODUCT_LIST_LOAD_SUCCESS = "PRODUCT_LIST_LOAD_SUCCESS";
export const PRODUCT_LIST_SORT_SUCCESS = "PRODUCT_LIST_SORT_SUCCESS";

export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";

export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";
